/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import componentes.TextPrompt;
import controlador.CtrLogin;
import controlador.CtrUsuario;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import modelo.MdlUsuario;

/**
 *
 * @author cdss2
 */
public class VstLogin extends javax.swing.JFrame {
    public static MdlUsuario usuarioLogin;
    /**
     * Creates new form VstLogin
     */
    public VstLogin() {
        initComponents();
        setLocationRelativeTo(this);
        configuraciones();
    }

    public void configuraciones() {
        TextPrompt holder = new TextPrompt("Ingrese Su Correo", txtCorreo);
        TextPrompt holder1 = new TextPrompt("Ingrese Su Contraseña", pswContrasena);
    }

    public void validarIngreso(){
        
        CtrUsuario ctru = new CtrUsuario();
        CtrLogin ctrl = new CtrLogin();
        int idUsuario = ctrl.validarIngreso(txtCorreo.getText(), pswContrasena.getText());
        
        if(idUsuario !=0){
            usuarioLogin = ctru.mostrarUsuario(idUsuario);
            ingresar(usuarioLogin);
        }else{
            pswContrasena.setFocusable(false);
            JOptionPane.showMessageDialog(null, "Usuario o Contraseña incorrecto", "Error", 1);
            pswContrasena.setFocusable(true);
        }
    }
    public void ingresar(MdlUsuario usuario) {
        dispose();
        vstMenu menu = new vstMenu();
        menu.setVisible(true);
    }
    
    public MdlUsuario getUsuario(){
        return this.usuarioLogin;
    }
    
    public void pasarAPassword(){
        pswContrasena.requestFocus(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLogin = new javax.swing.JPanel();
        lblIconoDecopinos = new javax.swing.JLabel();
        lblFondoLogin = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        lblContrasena = new javax.swing.JLabel();
        pswContrasena = new javax.swing.JPasswordField();
        lblTituloLogin = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panelLogin.setBackground(new java.awt.Color(255, 255, 255));
        panelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconoDecopinos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons/Logo Decopinos.png"))); // NOI18N
        panelLogin.add(lblIconoDecopinos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        lblFondoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondos/emerald-green-river-gradation-wallpaper-preview.jpg"))); // NOI18N
        lblFondoLogin.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        panelLogin.add(lblFondoLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, -1));

        lblUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons/usuario (2).png"))); // NOI18N
        panelLogin.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, -1, 40));

        txtCorreo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCorreo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        txtCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCorreoKeyReleased(evt);
            }
        });
        panelLogin.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, 250, 40));

        lblContrasena.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons/key.png"))); // NOI18N
        panelLogin.add(lblContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, -1, 40));

        pswContrasena.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        pswContrasena.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pswContrasena.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pswContrasenaKeyReleased(evt);
            }
        });
        panelLogin.add(pswContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 250, 250, 40));

        lblTituloLogin.setBackground(new java.awt.Color(0, 0, 0));
        lblTituloLogin.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        lblTituloLogin.setForeground(new java.awt.Color(51, 51, 51));
        lblTituloLogin.setText("INICIAR SESIÓN");
        panelLogin.add(lblTituloLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, -1, -1));

        btnIngresar.setBackground(new java.awt.Color(95, 148, 3));
        btnIngresar.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        btnIngresar.setText("Ingresar");
        btnIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnIngresarMousePressed(evt);
            }
        });
        panelLogin.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 360, 130, 40));

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        jLabel1.setText("¿Olvidaste tu contraseña?");
        panelLogin.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 320, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void btnIngresarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarMousePressed
        validarIngreso();
    }//GEN-LAST:event_btnIngresarMousePressed

    private void pswContrasenaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pswContrasenaKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            validarIngreso();
        }
    }//GEN-LAST:event_pswContrasenaKeyReleased

    private void txtCorreoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            pasarAPassword();
        }
    }//GEN-LAST:event_txtCorreoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VstLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VstLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VstLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VstLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VstLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblContrasena;
    private javax.swing.JLabel lblFondoLogin;
    private javax.swing.JLabel lblIconoDecopinos;
    private javax.swing.JLabel lblTituloLogin;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPasswordField pswContrasena;
    private javax.swing.JTextField txtCorreo;
    // End of variables declaration//GEN-END:variables
}
