/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.Producto;

import vista.Proveedor.*;
import vista.vistaUsuario.*;
import vista.*;

/**
 *
 * @author hamme
 */
public class vstProducto extends javax.swing.JPanel {

    /**
     * Creates new form pnlInicio
     */
    public vstProducto() {
        initComponents();
    }
    
    public void verInventario(){
        vstInventario panel = new vstInventario();
        vstMenu.panelContenedor(panel);
    }
    
    public void nuevoMarca(){
        vstAgregarEditarMarca panel = new vstAgregarEditarMarca();
        vstMenu.panelContenedor(panel);
    }
    
    public void verMarca(){
        vstVerMarca panel = new vstVerMarca();
        vstMenu.panelContenedor(panel);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContenedor = new componentes.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        pnlNuevoMarca = new componentes.PanelRound();
        jLabel2 = new javax.swing.JLabel();
        pnlVerInventario = new componentes.PanelRound();
        jLabel3 = new javax.swing.JLabel();
        pnlVerMarcas = new componentes.PanelRound();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(244, 244, 244));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlContenedor.setBackground(new java.awt.Color(255, 255, 255));
        pnlContenedor.setRoundBottomLeft(30);
        pnlContenedor.setRoundBottomRight(30);
        pnlContenedor.setRoundTopLeft(30);
        pnlContenedor.setRoundTopRight(30);
        pnlContenedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Producto");
        pnlContenedor.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 117, 91));

        pnlNuevoMarca.setRoundBottomLeft(30);
        pnlNuevoMarca.setRoundBottomRight(30);
        pnlNuevoMarca.setRoundTopLeft(30);
        pnlNuevoMarca.setRoundTopRight(30);
        pnlNuevoMarca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlNuevoMarcaMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nuevo Marca");

        javax.swing.GroupLayout pnlNuevoMarcaLayout = new javax.swing.GroupLayout(pnlNuevoMarca);
        pnlNuevoMarca.setLayout(pnlNuevoMarcaLayout);
        pnlNuevoMarcaLayout.setHorizontalGroup(
            pnlNuevoMarcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNuevoMarcaLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel2)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        pnlNuevoMarcaLayout.setVerticalGroup(
            pnlNuevoMarcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNuevoMarcaLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pnlContenedor.add(pnlNuevoMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 190, 90));

        pnlVerInventario.setRoundBottomLeft(30);
        pnlVerInventario.setRoundBottomRight(30);
        pnlVerInventario.setRoundTopLeft(30);
        pnlVerInventario.setRoundTopRight(30);
        pnlVerInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlVerInventarioMousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Ver Inventario");

        javax.swing.GroupLayout pnlVerInventarioLayout = new javax.swing.GroupLayout(pnlVerInventario);
        pnlVerInventario.setLayout(pnlVerInventarioLayout);
        pnlVerInventarioLayout.setHorizontalGroup(
            pnlVerInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVerInventarioLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel3)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        pnlVerInventarioLayout.setVerticalGroup(
            pnlVerInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVerInventarioLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel3)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pnlContenedor.add(pnlVerInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 190, 90));

        pnlVerMarcas.setRoundBottomLeft(30);
        pnlVerMarcas.setRoundBottomRight(30);
        pnlVerMarcas.setRoundTopLeft(30);
        pnlVerMarcas.setRoundTopRight(30);
        pnlVerMarcas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlVerMarcasMousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Ver Marcas");

        javax.swing.GroupLayout pnlVerMarcasLayout = new javax.swing.GroupLayout(pnlVerMarcas);
        pnlVerMarcas.setLayout(pnlVerMarcasLayout);
        pnlVerMarcasLayout.setHorizontalGroup(
            pnlVerMarcasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVerMarcasLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel5)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        pnlVerMarcasLayout.setVerticalGroup(
            pnlVerMarcasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVerMarcasLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel5)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pnlContenedor.add(pnlVerMarcas, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 190, 90));

        add(pnlContenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 620));
    }// </editor-fold>//GEN-END:initComponents

    private void pnlVerInventarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlVerInventarioMousePressed
        verInventario();
    }//GEN-LAST:event_pnlVerInventarioMousePressed

    private void pnlNuevoMarcaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNuevoMarcaMousePressed
        nuevoMarca();
    }//GEN-LAST:event_pnlNuevoMarcaMousePressed

    private void pnlVerMarcasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlVerMarcasMousePressed
        verMarca();
    }//GEN-LAST:event_pnlVerMarcasMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private componentes.PanelRound pnlContenedor;
    private componentes.PanelRound pnlNuevoMarca;
    private componentes.PanelRound pnlVerInventario;
    private componentes.PanelRound pnlVerMarcas;
    // End of variables declaration//GEN-END:variables
}
