/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.Proveedor;

public class vstAgregarEditarProveedor extends javax.swing.JPanel {

    public vstAgregarEditarProveedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContenedor = new componentes.PanelRound();
        panelRound1 = new componentes.PanelRound();
        lblTitulo = new javax.swing.JLabel();
        panelRound2 = new componentes.PanelRound();
        panelRound3 = new componentes.PanelRound();
        jSeparator1 = new javax.swing.JSeparator();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        panelRound4 = new componentes.PanelRound();
        jSeparator2 = new javax.swing.JSeparator();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        panelRound6 = new componentes.PanelRound();
        jSeparator4 = new javax.swing.JSeparator();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        panelRound5 = new componentes.PanelRound();
        jSeparator3 = new javax.swing.JSeparator();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        panelRound7 = new componentes.PanelRound();
        jSeparator5 = new javax.swing.JSeparator();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        panelRound8 = new componentes.PanelRound();
        jSeparator6 = new javax.swing.JSeparator();
        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        panelRound12 = new componentes.PanelRound();
        jLabel11 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        panelRound11 = new componentes.PanelRound();
        jLabel10 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        panelRound9 = new componentes.PanelRound();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        panelRound13 = new componentes.PanelRound();
        jLabel12 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(244, 244, 244));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlContenedor.setBackground(new java.awt.Color(255, 255, 255));
        pnlContenedor.setRoundBottomLeft(30);
        pnlContenedor.setRoundBottomRight(30);
        pnlContenedor.setRoundTopLeft(30);
        pnlContenedor.setRoundTopRight(30);
        pnlContenedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound1.setBackground(new java.awt.Color(255, 255, 255));
        panelRound1.setRoundBottomLeft(30);
        panelRound1.setRoundBottomRight(30);
        panelRound1.setRoundTopLeft(30);
        panelRound1.setRoundTopRight(30);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 24)); // NOI18N
        lblTitulo.setText("Agregar Proveedor");
        panelRound1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        panelRound2.setBackground(new java.awt.Color(255, 255, 255));
        panelRound2.setForeground(new java.awt.Color(255, 51, 51));
        panelRound2.setRoundBottomLeft(30);
        panelRound2.setRoundBottomRight(30);
        panelRound2.setRoundTopLeft(30);
        panelRound2.setRoundTopRight(30);
        panelRound2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound3.setBackground(new java.awt.Color(255, 255, 255));
        panelRound3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelRound3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 460, 10));

        jTextField1.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        panelRound3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 460, 20));

        jLabel1.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jLabel1.setText("Nombre");
        panelRound3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 110, 20));

        panelRound2.add(panelRound3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 630, 40));

        panelRound4.setBackground(new java.awt.Color(255, 255, 255));
        panelRound4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelRound4.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 460, 10));

        jTextField2.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        jTextField2.setBorder(null);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        panelRound4.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 460, 20));

        jLabel3.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jLabel3.setText("Identificacion");
        panelRound4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 110, 20));

        panelRound2.add(panelRound4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 630, 40));

        panelRound6.setBackground(new java.awt.Color(255, 255, 255));
        panelRound6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelRound6.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 460, 10));

        jTextField4.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        jTextField4.setBorder(null);
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        panelRound6.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 460, 20));

        jLabel5.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jLabel5.setText("Apellido");
        panelRound6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 110, 20));

        panelRound2.add(panelRound6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 630, -1));

        panelRound5.setBackground(new java.awt.Color(255, 255, 255));
        panelRound5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelRound5.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 460, 10));

        jTextField3.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        jTextField3.setBorder(null);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        panelRound5.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 460, 20));

        jLabel4.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jLabel4.setText("Telefono");
        panelRound5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 110, 20));

        panelRound2.add(panelRound5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 630, 40));

        panelRound7.setBackground(new java.awt.Color(255, 255, 255));
        panelRound7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelRound7.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 460, 10));

        jTextField5.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        jTextField5.setBorder(null);
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        panelRound7.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 460, 20));

        jLabel6.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jLabel6.setText("Correo");
        panelRound7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 110, 20));

        panelRound2.add(panelRound7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 630, 40));

        panelRound8.setBackground(new java.awt.Color(255, 255, 255));
        panelRound8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelRound8.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 460, 10));

        jTextField6.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        jTextField6.setBorder(null);
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        panelRound8.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 460, 20));

        jLabel7.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jLabel7.setText("Dirección");
        panelRound8.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 110, 20));

        panelRound2.add(panelRound8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 630, 40));

        panelRound12.setBackground(new java.awt.Color(255, 255, 255));
        panelRound12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jLabel11.setText("Tipo de identificacion");
        panelRound12.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, 20));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Tipo Identificacion", "C.C", "T.I", "PASAPORTE" }));
        panelRound12.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 170, 20));

        panelRound2.add(panelRound12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 630, 40));

        panelRound11.setBackground(new java.awt.Color(255, 255, 255));
        panelRound11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jLabel10.setText("Localidad");
        panelRound11.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 80, 20));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Ciudad" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        panelRound11.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 160, 20));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Pais" }));
        panelRound11.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 160, 20));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Departamento", "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelRound11.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 160, 20));

        panelRound2.add(panelRound11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 650, 40));

        panelRound9.setBackground(new java.awt.Color(255, 255, 255));
        panelRound9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 255, 0));
        jButton1.setText("Actualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelRound9.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));

        jButton2.setBackground(new java.awt.Color(0, 255, 153));
        jButton2.setText("Aceptar");
        panelRound9.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, -1, -1));

        jButton3.setBackground(new java.awt.Color(255, 51, 51));
        jButton3.setText("Cancelar");
        panelRound9.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, -1));

        panelRound2.add(panelRound9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 630, 40));

        panelRound13.setBackground(new java.awt.Color(255, 255, 255));
        panelRound13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jLabel12.setText("Producto");
        panelRound13.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 100, 20));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el producto" }));
        panelRound13.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 280, 20));

        panelRound2.add(panelRound13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 630, 40));

        panelRound1.add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 680, 570));

        pnlContenedor.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 620));

        add(pnlContenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 620));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel lblTitulo;
    private componentes.PanelRound panelRound1;
    private componentes.PanelRound panelRound11;
    private componentes.PanelRound panelRound12;
    private componentes.PanelRound panelRound13;
    private componentes.PanelRound panelRound2;
    private componentes.PanelRound panelRound3;
    private componentes.PanelRound panelRound4;
    private componentes.PanelRound panelRound5;
    private componentes.PanelRound panelRound6;
    private componentes.PanelRound panelRound7;
    private componentes.PanelRound panelRound8;
    private componentes.PanelRound panelRound9;
    private componentes.PanelRound pnlContenedor;
    // End of variables declaration//GEN-END:variables
}
