/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.Proveedor;

import javax.swing.JOptionPane;
import vista.*;
import static vista.vstMenu.usuarioPermisos;

/**
 *
 * @author hamme
 */
public class vstProveedor extends javax.swing.JPanel {

    /**
     * Creates new form pnlInicio
     */
    public vstProveedor() {
        initComponents();
    }
    

    public void verProveedor() {
        if (usuarioPermisos.get(1).getLeer() == 1) {
        vstVerProveedor panel = new vstVerProveedor();
        vstMenu.panelContenedor(panel);
         }else {
            mensajeSinPermiso();
        }
    }

    public void nuevoProveedor() {
        
        if (usuarioPermisos.get(1).getCrear()== 1) {
        vstAgregarEditarProveedor panel = new vstAgregarEditarProveedor(0);
        vstMenu.panelContenedor(panel);
         }else {
            mensajeSinPermiso();
        }
    }

     public void mensajeSinPermiso(){
           JOptionPane.showMessageDialog(null, "Este usuario no tiene permisos \npara ejecutar esta accion", "Error de permisos", 1);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new componentes.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        pnlVerProveedores = new componentes.PanelRound();
        jLabel3 = new javax.swing.JLabel();
        pnlNuevoUsuario = new componentes.PanelRound();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(244, 244, 244));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound1.setBackground(new java.awt.Color(255, 255, 255));
        panelRound1.setRoundBottomLeft(30);
        panelRound1.setRoundBottomRight(30);
        panelRound1.setRoundTopLeft(30);
        panelRound1.setRoundTopRight(30);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Proveedor");
        panelRound1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 180, 91));

        pnlVerProveedores.setRoundBottomLeft(30);
        pnlVerProveedores.setRoundBottomRight(30);
        pnlVerProveedores.setRoundTopLeft(30);
        pnlVerProveedores.setRoundTopRight(30);
        pnlVerProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlVerProveedoresMousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Ver Proveedores");

        javax.swing.GroupLayout pnlVerProveedoresLayout = new javax.swing.GroupLayout(pnlVerProveedores);
        pnlVerProveedores.setLayout(pnlVerProveedoresLayout);
        pnlVerProveedoresLayout.setHorizontalGroup(
            pnlVerProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlVerProveedoresLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(45, 45, 45))
        );
        pnlVerProveedoresLayout.setVerticalGroup(
            pnlVerProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVerProveedoresLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel3)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        panelRound1.add(pnlVerProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 190, 90));

        pnlNuevoUsuario.setRoundBottomLeft(30);
        pnlNuevoUsuario.setRoundBottomRight(30);
        pnlNuevoUsuario.setRoundTopLeft(30);
        pnlNuevoUsuario.setRoundTopRight(30);
        pnlNuevoUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlNuevoUsuarioMousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Nuevo Proveedor");

        javax.swing.GroupLayout pnlNuevoUsuarioLayout = new javax.swing.GroupLayout(pnlNuevoUsuario);
        pnlNuevoUsuario.setLayout(pnlNuevoUsuarioLayout);
        pnlNuevoUsuarioLayout.setHorizontalGroup(
            pnlNuevoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNuevoUsuarioLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(40, 40, 40))
        );
        pnlNuevoUsuarioLayout.setVerticalGroup(
            pnlNuevoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNuevoUsuarioLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel4)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        panelRound1.add(pnlNuevoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 190, 90));

        add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 620));
    }// </editor-fold>//GEN-END:initComponents

    private void pnlVerProveedoresMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlVerProveedoresMousePressed
        verProveedor();
    }//GEN-LAST:event_pnlVerProveedoresMousePressed

    private void pnlNuevoUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNuevoUsuarioMousePressed
        nuevoProveedor();
    }//GEN-LAST:event_pnlNuevoUsuarioMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private componentes.PanelRound panelRound1;
    private componentes.PanelRound pnlNuevoUsuario;
    private componentes.PanelRound pnlVerProveedores;
    // End of variables declaration//GEN-END:variables
}
