/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.vistaRolPer;

import vista.vistaRolPer.vstAgregarEditarRol;
import vista.vistaRolPer.vstVerRecursos;
import vista.vistaRolPer.vstVerRoles;
import vista.vstMenu;

/**
 *
 * @author hamme
 */
public class vstRolPer extends javax.swing.JPanel {

    /**
     * Creates new form pnlInicio
     */
    public vstRolPer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new componentes.PanelRound();
        lblTituloPanel = new javax.swing.JLabel();
        pnlInfoRecursos = new componentes.PanelRound();
        lblInfoRecursos = new javax.swing.JLabel();
        pnlVerRoles = new componentes.PanelRound();
        lblVerRoles = new javax.swing.JLabel();
        pnlCrearRol = new componentes.PanelRound();
        lblCrearRol = new javax.swing.JLabel();

        setBackground(new java.awt.Color(244, 244, 244));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound1.setBackground(new java.awt.Color(255, 255, 255));
        panelRound1.setRoundBottomLeft(30);
        panelRound1.setRoundBottomRight(30);
        panelRound1.setRoundTopLeft(30);
        panelRound1.setRoundTopRight(30);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloPanel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTituloPanel.setText("Rol Y per");
        panelRound1.add(lblTituloPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 117, 91));

        pnlInfoRecursos.setRoundBottomLeft(30);
        pnlInfoRecursos.setRoundBottomRight(30);
        pnlInfoRecursos.setRoundTopLeft(30);
        pnlInfoRecursos.setRoundTopRight(30);
        pnlInfoRecursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlInfoRecursosMousePressed(evt);
            }
        });

        lblInfoRecursos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblInfoRecursos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInfoRecursos.setText("Información Recursos");

        javax.swing.GroupLayout pnlInfoRecursosLayout = new javax.swing.GroupLayout(pnlInfoRecursos);
        pnlInfoRecursos.setLayout(pnlInfoRecursosLayout);
        pnlInfoRecursosLayout.setHorizontalGroup(
            pnlInfoRecursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoRecursosLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblInfoRecursos, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        pnlInfoRecursosLayout.setVerticalGroup(
            pnlInfoRecursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoRecursosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInfoRecursos, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelRound1.add(pnlInfoRecursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 190, 90));

        pnlVerRoles.setRoundBottomLeft(30);
        pnlVerRoles.setRoundBottomRight(30);
        pnlVerRoles.setRoundTopLeft(30);
        pnlVerRoles.setRoundTopRight(30);
        pnlVerRoles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlVerRolesMousePressed(evt);
            }
        });

        lblVerRoles.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblVerRoles.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVerRoles.setText("Ver Roles");

        javax.swing.GroupLayout pnlVerRolesLayout = new javax.swing.GroupLayout(pnlVerRoles);
        pnlVerRoles.setLayout(pnlVerRolesLayout);
        pnlVerRolesLayout.setHorizontalGroup(
            pnlVerRolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVerRolesLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(lblVerRoles, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        pnlVerRolesLayout.setVerticalGroup(
            pnlVerRolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVerRolesLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblVerRoles, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        panelRound1.add(pnlVerRoles, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 190, 90));

        pnlCrearRol.setRoundBottomLeft(30);
        pnlCrearRol.setRoundBottomRight(30);
        pnlCrearRol.setRoundTopLeft(30);
        pnlCrearRol.setRoundTopRight(30);
        pnlCrearRol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlCrearRolMousePressed(evt);
            }
        });

        lblCrearRol.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCrearRol.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCrearRol.setText("Crear Rol");

        javax.swing.GroupLayout pnlCrearRolLayout = new javax.swing.GroupLayout(pnlCrearRol);
        pnlCrearRol.setLayout(pnlCrearRolLayout);
        pnlCrearRolLayout.setHorizontalGroup(
            pnlCrearRolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCrearRolLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(lblCrearRol, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        pnlCrearRolLayout.setVerticalGroup(
            pnlCrearRolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCrearRolLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblCrearRol, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        panelRound1.add(pnlCrearRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 190, 90));

        add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 520));
    }// </editor-fold>//GEN-END:initComponents
    
    public void verRoles(){
        vstVerRoles panel = new vstVerRoles();
        vstMenu.panelContenedor(panel);
    }
    
    public void crearRol(){
    vstAgregarEditarRol panel = new vstAgregarEditarRol();
    vstMenu.panelContenedor(panel);
    }
    
    public void infoRecurso(){
    vstVerRecursos panel = new vstVerRecursos();
    vstMenu.panelContenedor(panel);
    }
    
    
    private void pnlVerRolesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlVerRolesMousePressed
         verRoles();
    }//GEN-LAST:event_pnlVerRolesMousePressed

    private void pnlCrearRolMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCrearRolMousePressed
        crearRol();
    }//GEN-LAST:event_pnlCrearRolMousePressed

    private void pnlInfoRecursosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlInfoRecursosMousePressed
        infoRecurso();
    }//GEN-LAST:event_pnlInfoRecursosMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblCrearRol;
    private javax.swing.JLabel lblInfoRecursos;
    private javax.swing.JLabel lblTituloPanel;
    private javax.swing.JLabel lblVerRoles;
    private componentes.PanelRound panelRound1;
    private componentes.PanelRound pnlCrearRol;
    private componentes.PanelRound pnlInfoRecursos;
    private componentes.PanelRound pnlVerRoles;
    // End of variables declaration//GEN-END:variables
}
