/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.Usuario;

import controlador.CtrAuxiliares;
import modelo.MdlUsuario;
import vista.vstMenu;
import static vista.vstMenu.usuarioPermisos;

/**
 *
 * @author hamme
 */
public class vstInformacionUsuario extends javax.swing.JPanel {

    MdlUsuario usuario = new MdlUsuario();

    /**
     * Creates new form pnlInicio
     */
    public vstInformacionUsuario(MdlUsuario usuario) {
        initComponents();
        this.usuario = usuario;
        inicio();
        ajustarPermisos();
    }

    public void ajustarPermisos() {

        if (usuarioPermisos.get(4).getEditar() == 0) {
            btnEditar.setVisible(false);
        }
    }

    public void inicio() {
        CtrAuxiliares ctra = new CtrAuxiliares();
        txtRol.setText(usuario.getRol().getNombre());
        txtTipoIdentificacion.setText(ctra.mostrarTipoIdentId(usuario.getTidenrificacion()));
        txtIdentificacion.setText(String.valueOf(usuario.getIdentificacion()));
        txtNombre.setText(usuario.getNombre());
        txtApellido.setText(usuario.getApellido());
        txtCorreo.setText(usuario.getLogin());
        txtDireccion.setText(usuario.getDireccion());
        txtTelefono.setText(usuario.getTelefono());
        txtCiudad.setText(usuario.getCiudad().getCiudad());
        txtFechaCreacion.setText(usuario.getFregistro().toString().substring(0, 11));
        unebla();
    }

    public void unebla() {
        txtRol.setEditable(false);
        txtTipoIdentificacion.setEditable(false);
        txtIdentificacion.setEditable(false);
        txtNombre.setEditable(false);
        txtApellido.setEditable(false);
        txtCorreo.setEditable(false);
        txtDireccion.setEditable(false);
        txtTelefono.setEditable(false);
        txtCiudad.setEditable(false);
        txtFechaCreacion.setEditable(false);

    }

    public void irEditar() {
        vstAgregarEditarUsuario panel = new vstAgregarEditarUsuario(usuario.getId());
        vstMenu.panelContenedor(panel);
        
    }

    public void cancer() {
        vstVerUsuario panel = new vstVerUsuario();
        vstMenu.panelContenedor(panel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new componentes.PanelRound();
        lblTitulo = new javax.swing.JLabel();
        panelRound2 = new componentes.PanelRound();
        panelRound3 = new componentes.PanelRound();
        jSeparator1 = new javax.swing.JSeparator();
        txtNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        panelRound4 = new componentes.PanelRound();
        jSeparator2 = new javax.swing.JSeparator();
        txtIdentificacion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        panelRound6 = new componentes.PanelRound();
        jSeparator4 = new javax.swing.JSeparator();
        txtApellido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        panelRound5 = new componentes.PanelRound();
        jSeparator3 = new javax.swing.JSeparator();
        txtTelefono = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        panelRound7 = new componentes.PanelRound();
        jSeparator5 = new javax.swing.JSeparator();
        txtCorreo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        panelRound8 = new componentes.PanelRound();
        jSeparator6 = new javax.swing.JSeparator();
        txtDireccion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        panelRound11 = new componentes.PanelRound();
        jLabel10 = new javax.swing.JLabel();
        txtFechaCreacion = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        panelRound9 = new componentes.PanelRound();
        btnEditar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        panelRound10 = new componentes.PanelRound();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        txtRol = new javax.swing.JTextField();
        panelRound13 = new componentes.PanelRound();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        txtTipoIdentificacion = new javax.swing.JTextField();
        panelRound12 = new componentes.PanelRound();
        jLabel11 = new javax.swing.JLabel();
        txtCiudad = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(244, 244, 244));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound1.setBackground(new java.awt.Color(255, 255, 255));
        panelRound1.setRoundBottomLeft(30);
        panelRound1.setRoundBottomRight(30);
        panelRound1.setRoundTopLeft(30);
        panelRound1.setRoundTopRight(30);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 24)); // NOI18N
        lblTitulo.setText("Información Usuario");
        panelRound1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        panelRound2.setBackground(new java.awt.Color(255, 255, 255));
        panelRound2.setForeground(new java.awt.Color(255, 51, 51));
        panelRound2.setRoundBottomLeft(30);
        panelRound2.setRoundBottomRight(30);
        panelRound2.setRoundTopLeft(30);
        panelRound2.setRoundTopRight(30);
        panelRound2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound3.setBackground(new java.awt.Color(255, 255, 255));
        panelRound3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelRound3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 460, 10));

        txtNombre.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        txtNombre.setBorder(null);
        panelRound3.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 460, 20));

        jLabel1.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jLabel1.setText("Nombre");
        panelRound3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 20));

        panelRound2.add(panelRound3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 630, 40));

        panelRound4.setBackground(new java.awt.Color(255, 255, 255));
        panelRound4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelRound4.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 460, 10));

        txtIdentificacion.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        txtIdentificacion.setBorder(null);
        panelRound4.add(txtIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 460, 20));

        jLabel3.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jLabel3.setText("Identificacion");
        panelRound4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 20));

        panelRound2.add(panelRound4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 630, 40));

        panelRound6.setBackground(new java.awt.Color(255, 255, 255));
        panelRound6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelRound6.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 460, 10));

        txtApellido.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        txtApellido.setBorder(null);
        panelRound6.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 460, 20));

        jLabel5.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jLabel5.setText("Apellido");
        panelRound6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 20));

        panelRound2.add(panelRound6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 630, -1));

        panelRound5.setBackground(new java.awt.Color(255, 255, 255));
        panelRound5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelRound5.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 460, 10));

        txtTelefono.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        txtTelefono.setBorder(null);
        panelRound5.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 460, 20));

        jLabel4.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jLabel4.setText("Telefono");
        panelRound5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 20));

        panelRound2.add(panelRound5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 630, 40));

        panelRound7.setBackground(new java.awt.Color(255, 255, 255));
        panelRound7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelRound7.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 460, 10));

        txtCorreo.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        txtCorreo.setBorder(null);
        panelRound7.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 460, 20));

        jLabel6.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jLabel6.setText("Correo");
        panelRound7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 20));

        panelRound2.add(panelRound7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 630, 40));

        panelRound8.setBackground(new java.awt.Color(255, 255, 255));
        panelRound8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelRound8.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 460, 10));

        txtDireccion.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        txtDireccion.setBorder(null);
        panelRound8.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 460, 20));

        jLabel7.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jLabel7.setText("Dirección");
        panelRound8.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 20));

        panelRound2.add(panelRound8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 630, 40));

        panelRound11.setBackground(new java.awt.Color(255, 255, 255));
        panelRound11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jLabel10.setText("F. Creación");
        panelRound11.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 20));

        txtFechaCreacion.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        txtFechaCreacion.setBorder(null);
        panelRound11.add(txtFechaCreacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 460, 20));
        panelRound11.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 460, 10));

        panelRound2.add(panelRound11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 630, 40));

        panelRound9.setBackground(new java.awt.Color(255, 255, 255));
        panelRound9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEditar.setBackground(new java.awt.Color(0, 255, 153));
        btnEditar.setText("Ir a Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        panelRound9.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        btnCancelar.setBackground(new java.awt.Color(204, 204, 204));
        btnCancelar.setText("Volver");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        panelRound9.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        panelRound2.add(panelRound9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 520, 310, 40));

        panelRound10.setBackground(new java.awt.Color(255, 255, 255));
        panelRound10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelRound10.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 460, 10));

        jLabel9.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jLabel9.setText("Rol");
        panelRound10.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 20));

        txtRol.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        txtRol.setBorder(null);
        txtRol.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRolKeyReleased(evt);
            }
        });
        panelRound10.add(txtRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 460, 20));

        panelRound2.add(panelRound10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 630, 40));

        panelRound13.setBackground(new java.awt.Color(255, 255, 255));
        panelRound13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelRound13.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 460, 10));

        jLabel12.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jLabel12.setText("T Identificación");
        panelRound13.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 20));

        txtTipoIdentificacion.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        txtTipoIdentificacion.setBorder(null);
        txtTipoIdentificacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTipoIdentificacionKeyReleased(evt);
            }
        });
        panelRound13.add(txtTipoIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 460, 20));

        panelRound2.add(panelRound13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 630, 40));

        panelRound12.setBackground(new java.awt.Color(255, 255, 255));
        panelRound12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jLabel11.setText("Localidad");
        panelRound12.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 20));

        txtCiudad.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        txtCiudad.setBorder(null);
        panelRound12.add(txtCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 460, 20));
        panelRound12.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 460, 10));

        panelRound2.add(panelRound12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 630, 40));

        panelRound1.add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 680, 570));

        add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 620));
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        irEditar();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        cancer();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtTipoIdentificacionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTipoIdentificacionKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoIdentificacionKeyReleased

    private void txtRolKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRolKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRolKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lblTitulo;
    private componentes.PanelRound panelRound1;
    private componentes.PanelRound panelRound10;
    private componentes.PanelRound panelRound11;
    private componentes.PanelRound panelRound12;
    private componentes.PanelRound panelRound13;
    private componentes.PanelRound panelRound2;
    private componentes.PanelRound panelRound3;
    private componentes.PanelRound panelRound4;
    private componentes.PanelRound panelRound5;
    private componentes.PanelRound panelRound6;
    private componentes.PanelRound panelRound7;
    private componentes.PanelRound panelRound8;
    private componentes.PanelRound panelRound9;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtFechaCreacion;
    private javax.swing.JTextField txtIdentificacion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRol;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTipoIdentificacion;
    // End of variables declaration//GEN-END:variables
}
