/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.Usuario;

import vista.*;

/**
 *
 * @author hamme
 */
public class vstUsuario extends javax.swing.JPanel {

    /**
     * Creates new form pnlInicio
     */
    public vstUsuario() {
        initComponents();
    }
    
    public void verUsuario(){
        vstVerUsuario panel = new vstVerUsuario();
        vstMenu.panelContenedor(panel);
    }
    
    public void nuevoUsuario(){
        vstAgregarEditarUsuario panel = new vstAgregarEditarUsuario(0);
        vstMenu.panelContenedor(panel);
    }
    
    public void verLogs(){
        vstVerLogs panel = new vstVerLogs();
         vstMenu.panelContenedor(panel);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new componentes.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        pnlLogsRegistrados = new componentes.PanelRound();
        jLabel2 = new javax.swing.JLabel();
        pnlVerUsurios = new componentes.PanelRound();
        jLabel3 = new javax.swing.JLabel();
        pnlNuevoUsuario = new componentes.PanelRound();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(244, 244, 244));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound1.setBackground(new java.awt.Color(255, 255, 255));
        panelRound1.setRoundBottomLeft(30);
        panelRound1.setRoundBottomRight(30);
        panelRound1.setRoundTopLeft(30);
        panelRound1.setRoundTopRight(30);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Usuarios");
        panelRound1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 180, 91));

        pnlLogsRegistrados.setRoundBottomLeft(30);
        pnlLogsRegistrados.setRoundBottomRight(30);
        pnlLogsRegistrados.setRoundTopLeft(30);
        pnlLogsRegistrados.setRoundTopRight(30);
        pnlLogsRegistrados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlLogsRegistradosMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Historial de logs");

        javax.swing.GroupLayout pnlLogsRegistradosLayout = new javax.swing.GroupLayout(pnlLogsRegistrados);
        pnlLogsRegistrados.setLayout(pnlLogsRegistradosLayout);
        pnlLogsRegistradosLayout.setHorizontalGroup(
            pnlLogsRegistradosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogsRegistradosLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel2)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        pnlLogsRegistradosLayout.setVerticalGroup(
            pnlLogsRegistradosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogsRegistradosLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        panelRound1.add(pnlLogsRegistrados, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 190, 90));

        pnlVerUsurios.setRoundBottomLeft(30);
        pnlVerUsurios.setRoundBottomRight(30);
        pnlVerUsurios.setRoundTopLeft(30);
        pnlVerUsurios.setRoundTopRight(30);
        pnlVerUsurios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlVerUsuriosMousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Ver Usuarios");

        javax.swing.GroupLayout pnlVerUsuriosLayout = new javax.swing.GroupLayout(pnlVerUsurios);
        pnlVerUsurios.setLayout(pnlVerUsuriosLayout);
        pnlVerUsuriosLayout.setHorizontalGroup(
            pnlVerUsuriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVerUsuriosLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel3)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        pnlVerUsuriosLayout.setVerticalGroup(
            pnlVerUsuriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVerUsuriosLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel3)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        panelRound1.add(pnlVerUsurios, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 190, 90));

        pnlNuevoUsuario.setRoundBottomLeft(30);
        pnlNuevoUsuario.setRoundBottomRight(30);
        pnlNuevoUsuario.setRoundTopLeft(30);
        pnlNuevoUsuario.setRoundTopRight(30);
        pnlNuevoUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlNuevoUsuarioMousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Nuevo Usuario");

        javax.swing.GroupLayout pnlNuevoUsuarioLayout = new javax.swing.GroupLayout(pnlNuevoUsuario);
        pnlNuevoUsuario.setLayout(pnlNuevoUsuarioLayout);
        pnlNuevoUsuarioLayout.setHorizontalGroup(
            pnlNuevoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNuevoUsuarioLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel4)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        pnlNuevoUsuarioLayout.setVerticalGroup(
            pnlNuevoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNuevoUsuarioLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel4)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        panelRound1.add(pnlNuevoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 190, 90));

        add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 620));
    }// </editor-fold>//GEN-END:initComponents

    private void pnlVerUsuriosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlVerUsuriosMousePressed
        verUsuario();
    }//GEN-LAST:event_pnlVerUsuriosMousePressed

    private void pnlLogsRegistradosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLogsRegistradosMousePressed
        verLogs();
    }//GEN-LAST:event_pnlLogsRegistradosMousePressed

    private void pnlNuevoUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNuevoUsuarioMousePressed
       nuevoUsuario();
    }//GEN-LAST:event_pnlNuevoUsuarioMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private componentes.PanelRound panelRound1;
    private componentes.PanelRound pnlLogsRegistrados;
    private componentes.PanelRound pnlNuevoUsuario;
    private componentes.PanelRound pnlVerUsurios;
    // End of variables declaration//GEN-END:variables
}
