/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.RolPer;

import javax.swing.JOptionPane;
import vista.*;
import static vista.vstMenu.usuarioPermisos;

/**
 *
 * @author hamme
 */
public class vstRolPer extends javax.swing.JPanel {

    /**
     * Creates new form pnlInicio
     */
    public vstRolPer() {
        initComponents();
    }

    public void verRol() {

        if (usuarioPermisos.get(3).getLeer() == 1) {
            vstVerRol panel = new vstVerRol();
            vstMenu.panelContenedor(panel);
        } else {
            mensajeSinPermiso();
        }
    }

    public void nuevoRol() {
        if (usuarioPermisos.get(3).getCrear() == 1) {
            vstAgregarEditarRol panel = new vstAgregarEditarRol(0);
            vstMenu.panelContenedor(panel);
        } else {
            mensajeSinPermiso();
        }
    }

    public void mensajeSinPermiso() {
        JOptionPane.showMessageDialog(null, "Este usuario no tiene permisos \npara ejecutar esta accion", "Error de permisos", 1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new componentes.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        pnlNuevoRol = new componentes.PanelRound();
        jLabel2 = new javax.swing.JLabel();
        pnlVerRoles = new componentes.PanelRound();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(244, 244, 244));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound1.setBackground(new java.awt.Color(255, 255, 255));
        panelRound1.setRoundBottomLeft(30);
        panelRound1.setRoundBottomRight(30);
        panelRound1.setRoundTopLeft(30);
        panelRound1.setRoundTopRight(30);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Rol");
        panelRound1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 117, 91));

        pnlNuevoRol.setRoundBottomLeft(30);
        pnlNuevoRol.setRoundBottomRight(30);
        pnlNuevoRol.setRoundTopLeft(30);
        pnlNuevoRol.setRoundTopRight(30);
        pnlNuevoRol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlNuevoRolMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nuevo Rol");

        javax.swing.GroupLayout pnlNuevoRolLayout = new javax.swing.GroupLayout(pnlNuevoRol);
        pnlNuevoRol.setLayout(pnlNuevoRolLayout);
        pnlNuevoRolLayout.setHorizontalGroup(
            pnlNuevoRolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNuevoRolLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel2)
                .addContainerGap(77, Short.MAX_VALUE))
        );
        pnlNuevoRolLayout.setVerticalGroup(
            pnlNuevoRolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNuevoRolLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        panelRound1.add(pnlNuevoRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 190, 90));

        pnlVerRoles.setRoundBottomLeft(30);
        pnlVerRoles.setRoundBottomRight(30);
        pnlVerRoles.setRoundTopLeft(30);
        pnlVerRoles.setRoundTopRight(30);
        pnlVerRoles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlVerRolesMousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Ver Roles");

        javax.swing.GroupLayout pnlVerRolesLayout = new javax.swing.GroupLayout(pnlVerRoles);
        pnlVerRoles.setLayout(pnlVerRolesLayout);
        pnlVerRolesLayout.setHorizontalGroup(
            pnlVerRolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVerRolesLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel3)
                .addContainerGap(84, Short.MAX_VALUE))
        );
        pnlVerRolesLayout.setVerticalGroup(
            pnlVerRolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVerRolesLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel3)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        panelRound1.add(pnlVerRoles, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 190, 90));

        add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 620));
    }// </editor-fold>//GEN-END:initComponents

    private void pnlVerRolesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlVerRolesMousePressed
        verRol();
    }//GEN-LAST:event_pnlVerRolesMousePressed

    private void pnlNuevoRolMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNuevoRolMousePressed
        nuevoRol();
    }//GEN-LAST:event_pnlNuevoRolMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private componentes.PanelRound panelRound1;
    private componentes.PanelRound pnlNuevoRol;
    private componentes.PanelRound pnlVerRoles;
    // End of variables declaration//GEN-END:variables
}
